import type { Dict } from './types'

export const en: Dict = {
  nav: { chapter: 'Chapter', sound: 'Sound' },
  hero: {
    role: 'Game Designer & Computer Engineer',
    tagline: 'I design puzzles, economies and feel — then I build them.',
    scroll: 'Scroll to play',
  },
  about: {
    title: 'Tutorial',
    stepLabel: 'Step',
    steps: [
      {
        k: 'Who',
        t: 'Engineer brain, designer heart.',
        d: 'Computer Engineering graduate and Game Designer with end-to-end production experience across commercial mobile titles, systems design and algorithmic game mechanics.',
      },
      {
        k: 'Built',
        t: 'One game, from zero to Google Play.',
        d: 'Prime Path is my solo mobile puzzle: production GDD, a solver that guarantees every level is solvable, and a hybrid economy — now in live playtesting.',
      },
      {
        k: 'Craft',
        t: 'Pacing, balance and cognitive traps.',
        d: 'Level pacing, combat balancing, tutorial curricula, tactile feedback — the invisible things that make a game feel right.',
      },
      {
        k: 'Studio',
        t: 'Gnarly Game Studio.',
        d: 'Levels, boss pitches, competitor research, playable-ad analytics and live balancing on a flagship cover-shooter.',
      },
      {
        k: 'Data',
        t: 'Design that listens to players.',
        d: 'Funnel telemetry, churn tracking and Remote Config tuning, so decisions come from what players actually do.',
      },
    ],
  },
  chapters: {
    hero: 'Boot',
    about: 'Tutorial',
    prime: 'Prime Path',
    experience: 'Pacing',
    skills: 'Perks',
  },
  ach: {
    unlocked: 'Achievement unlocked',
    items: {
      explorer: 'Explorer — you started scrolling',
      student: 'Quick Learner — tutorial complete',
      fullbuild: 'Full Build — all four perks equipped',
      solver: 'Puzzle Solver — you cracked a Prime Path level',
    },
  },
  prime: {
    title: 'Prime Path',
    sub: 'A mathematical logic puzzle — designed, built and shipped solo.',
    chip: 'Live on Google Play · playtesting',
    facts: [
      { n: '290', l: 'line production GDD' },
      { n: '2×2 → 5×5', l: 'boards, every level provably solvable' },
      { n: '1–10', l: 'automatic difficulty rating' },
      { n: '13', l: 'stage tutorial curriculum' },
    ],
    trapsTitle: 'Cognitive traps',
    traps: [
      { t: 'Fork / greed', d: 'The tempting route that dead-ends.' },
      { t: 'Blocked transit', d: 'Cells you can see but cannot cross.' },
      { t: 'Mirror', d: 'Symmetry that lies about the answer.' },
      { t: 'Center contention', d: 'Every path wants the same cell.' },
    ],
    shotsTitle: 'From the store',
    shotSoon: 'Screenshot slot',
    stack: 'React 19 · TypeScript · Capacitor · Supabase · Firebase',
  },
  demo: {
    title: 'Try it',
    level: 'Level',
    levelNames: ['Tutorial', 'Level 33', 'Level 57'],
    rule: 'Swipe across neighbouring cells (diagonals too). The numbers must add up to a target, and the swipe needs at least one ★ prime.',
    targets: 'Targets',
    idle: 'Drag across cells, or tap them one by one and press Check. Tutorial: no lives are lost.',
    win: 'All targets reached! The solver confirms this level is solvable.',
    stuck: 'Dead end — the remaining targets cannot be reached. Undo a swipe.',
    undo: 'Undo',
    reset: 'Reset',
    check: 'Check',
    solver: 'Show solver',
    live: (n) => `Sum ${n}`,
    noPrime: 'Right sum, but no ★ prime in the swipe.',
    noMatch: (n) => `${n} is not one of the targets.`,
    solved: (t) => `${t} reached!`,
    stats: (s, n) => `Solver: ${s.join(' / ')} valid swipes per target · ${n.toLocaleString('en')} states searched`,
  },
  exp: {
    eyebrow: 'Experience',
    title: 'Gnarly Game Studio',
    role: 'Game Designer (Intern) · July – September 2026',
    axis: ['calm', 'intense'],
    items: [
      {
        k: 'Levels',
        t: 'Complete level designs, with a stress curve.',
        d: 'Authored full levels, mapped player stress and pacing, and presented pacing reports directly to the lead designers.',
      },
      {
        k: 'Boss pitches',
        t: 'Ten boss mechanics pitched for a turn-based title.',
        d: 'One of them was approved and implemented into the live game.',
        stat: { n: '10 → 1', l: 'pitched → shipped' },
      },
      {
        k: 'Market',
        t: 'Competitor research across top-chart mobile titles.',
        d: 'Evaluated monetization models and turned them into actionable design reports.',
      },
      {
        k: 'Playable ads',
        t: 'Fail-states that make ads convert.',
        d: 'Analysed playable-ad test data and designed fail-state scenarios that improved creative engagement and conversion.',
      },
      {
        k: 'Balance',
        t: 'Combat scaling and rogue-lite perk cards.',
        d: 'Balanced combat scaling numbers, base stats and perk-card progression on a live flagship cover-shooter.',
      },
      {
        k: 'QA',
        t: 'Daily QA on every new batch of levels.',
        d: 'Removed collision glitches, unintended shortcut solutions and sudden difficulty spikes before they reached players.',
      },
      {
        k: 'Prototypes',
        t: 'Mechanics proven before engineering sprints.',
        d: 'Prototyped experimental mechanics and scenes in Unity with AI-assisted scripting to validate feasibility early.',
      },
    ],
  },
  skills: {
    eyebrow: 'Perks',
    title: 'Pick your build',
    sub: 'Tap a card to equip it. Equip all four for the full build.',
    equip: 'Equip',
    equipped: 'Equipped',
    count: (n, total) => `${n}/${total} perks equipped`,
    cards: [
      {
        rarity: 'legendary',
        name: 'Game Design Systems',
        tag: 'Core build',
        items: [
          'Production GDD authoring',
          'Core, meso & macro loops',
          'Level design & difficulty pacing',
          'Cognitive trap & puzzle mechanics',
          'Combat & stat-scaling balance',
          'Onboarding & tutorial curriculum',
          'Game feel: audio & haptics',
        ],
      },
      {
        rarity: 'epic',
        name: 'Economy & Monetization',
        tag: 'Live ops',
        items: [
          'Hybrid IAP + ads models',
          'Tiered catalog & anchor pricing',
          'Progression-gated ad placement',
          'Retention meta: codex, streaks, pass',
          'Competitor benchmarking & teardowns',
          'Playable-ad analytics',
        ],
      },
      {
        rarity: 'rare',
        name: 'Engines & Code',
        tag: 'Builder',
        items: [
          'Unity 2D/3D & C#',
          'TypeScript & React 19',
          'Capacitor for Android',
          'Rapid prototyping, AI-assisted',
          'Git branch workflows',
        ],
      },
      {
        rarity: 'rare',
        name: 'Analytics, QA & Backend',
        tag: 'Data-driven',
        items: [
          'Funnel telemetry & churn (Firebase, GameAnalytics)',
          'Live tuning with Remote Config',
          'Level QA & unintended-solution spotting',
          'Supabase (PostgreSQL & Edge Functions)',
          'Python FastAPI, REST & Postman',
        ],
      },
    ],
  },
}
